### ISSUE TITLE
New VIP request

### ISSUE THREAD

**Issue by Clio75** [fieldrndservices/libssh2-labview#1]
Hi, 
I'm trying your code, but Like to have a new VIP file for installing these files correct on my computer.

Thanx 
Aleksander

**Comment by volks73** [comment]
Thank you for your request. I have attached a VIP to this comment that you can try. Note, I had to change the file extension from `.vip` to `.zip` to attach to this comment. Please change the file extension back to `.vip` after downloading. This VIP is from the latest revision and should work for LabVIEW 2009 or newer.

[field_rnd_services_libssh2-master.zip](https://github.com/fieldrndservices/libssh2-labview/files/4375466/field_rnd_services_libssh2-master.zip)

**Comment by volks73** [comment]
I am going to close this issue, as it appears the attached ZIP/VIP has answered this question/
