### ISSUE TITLE
Session Palette wrongly using Agent VIs

### ISSUE THREAD

**Issue by Clio75** [fieldrndservices/libssh2-labview#2]
Hi, And thanx for making this toolkit. 

I'm trying to use it, but there seams to be missing something. 
![image](https://user-images.githubusercontent.com/8381796/77522885-407f1f00-6e85-11ea-9e36-fc09bedef3a7.png)

According to your snipplets in the Read.me There looks like there are a init season : 
![image](https://user-images.githubusercontent.com/8381796/77523021-69071900-6e85-11ea-948d-6b521e43335a.png)

Also in the Connect.VI there are no input that can tell where to connect. 

Pleas look into this and let me know what I do wrong :) 
Thanx

**Comment by volks73** [comment]
I appear to have copied over the SSH Agent-related VIs for the Session palette instead of the much more needed Session VIs. Please give me a moment and I will fix this issue and generate a new VIP. Everything should be much more clear this point.

**Comment by volks73** [comment]
It appears the Agent VIs were being used in multiple sub-palettes, not just the Session sub-palette. I have created a new ZIP/VIP and tested the installation with LabVIEW 2018. The palettes appear correct for this VIP (build 1.0.0.8) on my system. I have attached the new VIP as a ZIP. Please change the file extension after downloading from ZIP to VIP for installation.


[field_rnd_services_libssh2-1.0.0.8.zip](https://github.com/fieldrndservices/libssh2-labview/files/4381425/field_rnd_services_libssh2-1.0.0.8.zip)

**Comment by Clio75** [comment]
Thanx, Now it is correct.
