### ISSUE TITLE
Password authentication failed

### ISSUE THREAD

**Issue by GloaLette** [fieldrndservices/libssh2-labview#46]
When I try to login I get an error message:
Field_RnD_Services_LIBSSH2_Toolkit.lvlib:Session.lvclass:Password Authentication.vi<ERR>
[Authentication Error]
This is since I updated my system for some vulnerability issues.
Is there a chance that the tool gets an update that it support newer algorithms?

**Comment by volks73** [comment]
@GloaLette, It is certainly possible to build with support for newer algorithms. The LIBSSH2-LabVIEW toolkit is a LabVIEW "wrapper" around the [libssh2lv](https://github.com/fieldrndservices/libssh2lv) library, which is a LabVIEW friendly C wrapper around the [libssh2](https://www.libssh2.org/) library. The libssh2 and libssh2lv libraries are built using OpenSSL v1.1.1l. It appears [libssh2 v1.10.0 added support for OpenSSL v3.0](https://www.libssh2.org/changes.html), but there is also an OpenSSL v1.1.1m released around the same time. Thus, it looks like the libssh2lv library just needs to update the build to use a newer version of OpenSSL.

What algorithms do you need supported?

**Comment by GloaLette** [comment]
Hi, sorry for the late response.
The machine I want to login use openssl 3.0.0.7 and the algorithm is sha-256.
Would be great when you can create a build and I can test it if its working.

**Comment by volks73** [comment]
@GloaLette I have [created an issue](https://github.com/fieldrndservices/libssh2lv/issues/11) in the [libssh2lv](https://github.com/fieldrndservices/libssh2lv) project to bump the OpenSSL dependency version. Your issue cannot be resolved within this LabVIEW toolkit, but must be resolved in the build and dependencies of the libssh2lv project, which is a dependency of this LabVIEW toolkit. I will investigate and work on building the libssh2lv shared library with the newer version of OpenSSL.
