### ISSUE TITLE
Build Application

### ISSUE THREAD

**Issue by Clio75** [fieldrndservices/libssh2-labview#54]
Hi, 

I trying to build an application. But SSH will not open : 

_CLEANUP ! 
Something whent wrong. 
TCP Close Connection in Field_RnD_Services_LIBSSH2_Toolkit.lvlib:Session.lvclass:Disconnect.vi->TestActor_JRRC.lvlib:SSH_JRRC.lvclass:Close.vi->TestActor_JRRC.lvlib:TestActor_JRRC.lvclass:Actor Core.vi:5880001->Actor Framework.lvlib:Actor.lvclass:Actor.vi:6640015->Actor Framework.lvlib:Actor.lvclass:Actor.vi.ACBRProxyCaller.E650001D
Open SSH connection : 
Disconnected  to  IP :  10.0.10.88_

So the question is, What do i need to include in the build script to ensure that this application is running on other Windows computers ? 
Thanx

**Comment by volks73** [comment]
@Clio75 I am assuming you have created a "Build Specification" in the Project Explorer for "My Computer" to build an executable on Windows. In this case, you need to ensure that the DLLs for this toolkit are always included. These are the `libssh2lv.dll` and `libssh2lv-x64.dll` located in "Dependencies->vi.lib->Field_RnD_Services_LIBSSH2_Toolkit.lvlib->Support" within the Project Explorer for your project referencing this toolkit. I would simply _copy_, not move, all of the DLLs, dylibs, and .so, to a folder under the "My Computer" target, like a `libraries` virtual or auto-populated folder. This will make them available in the Build Specification for the Application. From there, you can add them to the "Support" folder or the same folder as the built `.exe`.

**Comment by Clio75** [comment]
I was able to make it work :) 
Thanx for your advice :)
